### ISSUE TITLE
Remove ATTACK.md from each app and add it's content into README.md

### ISSUE THREAD

**Issue by rafaveira3** [globocom/secDevLabs#163]

**Comment by Krlier** [comment]
This issue was closed thanks to all of these PRs

A1
Copy-n-Paste - #165 

A2
Saidajaula Monster FIt - #229
Insecure Go Project - #230

A3
Snake Pro - #231 

A4
ViniJR Blog - #232 

A5
Ecommerce API - #234 

A6
Misconfigured Wordpress - #236 

A7
Gossip World - #237 

A8
Amarelo Designs - #238 

A9
Cimentech - #239 

A10
Games Irados - #240
