### ISSUE TITLE
A9 Cimentech not exploitable on Linux machines

### ISSUE THREAD

**Issue by rafaveira3** [globocom/secDevLabs#212]
After building the app, it is not possible to follow the attack narrative and reproduce the exploitation.

Maybe docker running in Linux has some different protections.

Issue found by @mbenford . Thanks for that! 👏🏻

**Comment by Krlier** [comment]
Nice catch @rafaveira3!

I did some testing and I was able to reproduce this issue. The problem is that some Ruby installations on some Linux systems may come without the `Highline` gem, which is needed to properly run the exploit.

I took the liberty of creating a few steps on how to solve it, and added a link to this issue on A9's `README.md`:

As we can see from the image below, I'm not able to properly run the exploit because of the `Highline` gem:
![a9 - 1](https://user-images.githubusercontent.com/40367872/57778533-a134bb80-76fa-11e9-83d0-d416c536f825.png)

This issue can be fixed by running the gem installation command and, yes, you need to run it as `sudo` to work:
```sh
sudo gem install highline
```
![a9 - 2](https://user-images.githubusercontent.com/40367872/57778773-1ef8c700-76fb-11e9-8979-12544ffb15b4.png)


After installing the missing gem, I was able to properly run the exploit, as shown by the image below:
![a9 - 3](https://user-images.githubusercontent.com/40367872/57778721-0b4d6080-76fb-11e9-88b3-0651e35b89f9.png)

If you did all the steps above and is still facing some difficulty running the exploit, please have a look at the troubleshooting section [here].

[here]: https://github.com/dreadlocked/Drupalgeddon2

**Comment by Takehime** [comment]
I had this same issue on MacOS, and these steps worked for me as well.
