### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by vnvyvu** [globocom/secDevLabs#430]
i cant create new account

![image](https://user-images.githubusercontent.com/22812601/93630173-bcf95180-fa13-11ea-9496-89dc3b2d77e3.png)

**Comment by Krlier** [comment]
Hi, @vnvyvu! Thanks for reaching out to us!

I can see you're trying to create an account in our TicTacToe A5 app, but this one has a particularity. During the development phase of the app, we faced a bug that would not allow us to connect to `http://localhost:10005/`. To overcome that, we need to access it with a  `.` in the URL, like this: `http://localhost.:10005/`.

Would you mind trying to access the app again using the following URL to see if the problem is fixed: `http://localhost.:10005/`.

**Comment by Krlier** [comment]
I'm closing this issue due to long inactivity.

@vnvyvu, if you're still facing any issues running the app, please feel free to reopen this issue or create another one.
